spring.application.name=isrpo-lab2

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true

management.metrics.tags.application=isrpo-lab2

# Logging
logging.level.ru.itmo.isrpo=DEBUG
logging.level.com.github.loki4j=DEBUG

